spring:
  datasource:
    username: root
    password: lhang
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.125/jpa
  jpa:
    hibernate:
#    更新或者创建数据表结构
      ddl-auto: update
#      控制台显示sql
    show-sql: true
